name: Build and Test eyecite API Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t eyecite-api .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name eyecite-api-test eyecite-api
          sleep 10

      - name: Test /extract endpoint
        run: |
          curl -X POST "http://localhost:8000/extract" \
            -H "Content-Type: application/json" \
            -d '{"text": "See 410 U.S. 113 (1973)."}'

      - name: Show container logs on failure
        if: failure()
        run: docker logs eyecite-api-test

      - name: Stop container
        if: always()
        run: docker stop eyecite-api-test && docker rm eyecite-api-test
